categories_prompts = {
    
    'Обмен валюты': ['dollar,dollar bill,arrow,coin,rubble,exchange,currency exchange',
                     'ATM machine,blue,dollar,coin,gold goin,exchange,currency exchange',
                     'dollar,euro,ruble,currency notes from different countries,exchange,currency exchange',
                     'rasing chart,upwise trend,orange line,exchange rate,banknote',
                     'globe,blue planet,Earth,arrow,line,exchange,currency exchange',
                     'globe,planet,arrow,line,money exchange,swap,change,exchange,currency exchang,orange,light blue,deep blue,white',
                     'gold bag of money,banknote,dollars,money,currency exchange,ruble,euro,exchange rate,orange,light blue,deep blue,white',
                     'blue chart,line,rising trend,green arrow,profitable,bag of money,currency exchange,exchange,white,orange',
                     'chart,banknote,line,increasing trend,green arrow,profitable,blue bills,pack of blue bills,silver coins,currency exchange,exchange',
                     'coin,banknote,exchange,currency exchange,profitable,chart,increasing trend,percentage sign,green line',
                     'different currencies, banknotes, calculator, dynamic exchange rate figures,currency exchange, exchange'],
    
    'Кредит': ['stack,stack of coins,stack of bills,credit,profitably,loan,loan approval',
               'handshake,contract,beneficial,bills,loan,loan approval',
               'green confirmation check mark,loan,loan approval,bundle of bills,banknotes',
               'contract,confirmation tick,handshake,loan,loan approval,bag of money',
               'house keys,check mark,confirmation,loan,loan approval',
               'travel,vacation,sea,sun,beach,beach umbrella,towel,beach flip-flops,blue,light blue,orange,white,green,yellow',
               'travel,weekend,sea,sun,beach,chaise longue,beach chair,beach ball,blue,light blue,orange,white,green,yellow',
               'student loan,education,university,graduate hat',
               'credit,tuition,education,graduate hat,book,pen,blue,orange,white,black',
               'new year,gift box,red box,white ribbon bow,Santa claus hat,snow,snowdrifts',
               'new year,gift box,blue box,Christmas tree,snow,snowdrifts'],
    
    'Карта': ['card,gazprombank logo,mobile phone,smartphone,black phone',
              'card,gazprombank logo,white smartphone,open screen,blue screen',
              'credit card,gazprombank logo,gazpromcard,percent,percent sign,profitably,card',
              'credit card,gazprombank logo,gift box,blue box,Christmas tree,snow,snowdrifts',
              'credit card,gift box,orange box,white ribbon bow,percent sign,profitably',
              'card,gazprombank logo,confetti,banknotes,gold coins',
              'card,gazprombank logo,holiday,lightnings,festive hat,blue,white,silver,light blue',
              'cards,two cards,white,black,silver chip,proection, 3D',
              'cards,two cards,silver,gold,silver chip,proection, 3D',
              'card,payment,terminal,ATM machine,black,while,silver',
              'card,payment,terminal,contactless payment,online payment,attach the card to the terminal'],
    
    'Счета_вклады': ['safe,safety,safe locker,gold,gold coins',
                     'safe,safety,safe locker,silver,silver coins',
                     'safe,safety,safe locker,pack of banknotes,blue,money,bills',
                     'bank,money,bank building,coin,banknote,blue,white,light blue,orange',
                     'bank,bank building,banknotes,confetti,profitably',
                     'golden piggy bank,banknotes',
                     'golden piggy bank,coins',
                     'locker,lock,money lock,bill lock,coin lock,blue',
                     'blue shield,banknotes,money',
                     'silver shield,banknotes,money'],
    
    'Ипотека': ['house,river,tree,windows,stairs,blue sky,white house',
                'sun,white house,without doors,without windows,lightnings,confetti',
                'grey house key,gift,red ribbow bow',
                'grey house key,gift,red ribbow bow,confetti',
                'yellow house key,gift,red ribbow bow',
                'blue house,black roof,building,tree',
                'two buildings,tree',
                'house,roof,ribbon bow,gift',
                'orange house,blue roof,white ribbon bow'],
    
    'Автокредит': ['blue car,percent sign,red ribbon bow',
                   'two cars,confetti,gift,red,blue,silver',
                   'two cars,confetti,gift,orange,blue,gold',
                   'three cars,three,percent sign,percent,orange,black,white,blue,light blue',
                   'car,red car,fast driving,smoke,orange lightning',
                   'car,blue car,fast driving,smoke,silver confetti',
                   'black steering wheel,big gift box,red gift box,ribbon bow',
                   'black steering wheel,gold silver confetti,orange ribbon bow',
                   'black steering wheel,blue percent sign,profitably',
                   'car,percent sign'],
    
    'Страхованиe': ['two shields,shield,blue shield,orange shield',
                    'safe,safety,two hands,promise, care, hand,hands in the begging pose',
                    'protection, protective sign,shield,blue',
                    'shiled,silver shield,car,protection',
                    'shield,blue shield,house,protection',
                    'black steering wheel,gold shield,protection',
                    'black steering wheel,blue shield,protection',
                    'shield,money,coin,banknotes,bills',
                    'locker,shield,safety,protection,blue,light blue,orange,white']
}
