version: "3.8"

volumes:
  pgdata:

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./backend/api-service
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/dev
    depends_on:
      - db
    restart: always

  ml:
    build:
      context: ./backend/ml
    ports:
      - 50051:50051
