categories_prompts = {
        'currency_exchange': ['dollar,bill',
                              'dollar,coin,rubble',
                              'ATM machine',
                              'ATM machine,coins',
                              'ATM machine,man',
                              'ATM machine,gold', 
                              'ATM machine,dollar',
                              'sheet of paper,coins',
                              'calculator,coins', 
                              'graph,line,chart,coins',
                              'coins,chart,line',
                              'diagram,calculator',
                              'calculator,line',
                              'planet,calculator',
                              'planet,coin',
                              'planet,Earth,line',
                              'Earth,coins',
                              'globe,coins',
                              'globe',
                              'globe,line',
                              'bag of money,calculator',
                              'bag of money,planet', 
                              'bag of money,globe',
                              'chart,bag of coins',
                              'green line,bag of money'],
    
        'credit': ['coins,bills',
                   'sheet of paper,pen',
                   'sheet of paper,calculator', 
                   'calculator,pen',
                   'calculator,coins',
                   'pen,coins,sheet of paper', 
                   'sheet of paper,coins',
                   'handshake,paper',
                   'handshake',
                   'check mark,coins',
                   'bag of money,check mark',
                   'check mark,sheet of paper',
                   'check mark,coins',
                   'bank,bank building',
                   'bank,coins',
                   'bank',
                   'bank,coin',
                   'armchair,coins',
                   'armchair,coin,money',
                   'shopping bag,coins',
                   'bag of money',
                   'cardholder,money',
                   'sheet of paper'],
    
        'card': ['credit card,mobile phone',
                 'credit card,smartphone',
                 'credit card',
                 'credit card,gift box',
                 'credit card,ribbon',
                 'credit card,vase with flowers',
                 'payment card,coins',
                 'payment card,banknotes',
                 'credit card,ribbon,bow',
                 'credit card,terminal',
                 'payment card,glass of coffee',
                 'credit card,cup of coffee',
                 'credit card,car',
                 'credit card,bow tie',
                 'credit card,coins',
                 'credit card,flower',
                 'wallet,credit card',
                 'wallet,payment card',
                 'cardholder',
                 'credit card,shopping bag'],

        'accounts_deposits': ['safe locker,coins',
                              'safe locker',
                              'piggy bank,banknotes',
                              'piggy bank,coins',
                              'safe locker,banknotes',
                              'bank,bank building',
                              'safe locker,wallet',
                              'safe locker,briefcase',
                              'briefcase,sheet of paper',
                              'briefcase',
                              'briefcase,coins',
                              'wallet,coins',
                              'lock,wallet',
                              'lock,briefcase',
                              'graph,diagram,bar chart',
                              'bar chart',
                              'line,graph,coins',
                              'chart,coins',
                              'bar chart,coins',
                              'bar chart,wallet',
                              'graph,wallet',
                              'line,diagram,chart,bar chart',
                              'diagram,bar chart,wallet',
                              'line,graph',
                              'pie chart,coin',
                              'wallet,cofee',
                              'briefcase,calculator'],

        'mortgage': ['house,tree',
                     'house',
                     'house key,house',
                     'home,house key',
                     'river,tree,house',
                     'house,home,swimming pool',
                     'armchair,heart',
                     'chair,desk',
                     'chair,lamp,desk',
                     'desk,lamp',
                     'chair,lamp',
                     'house,lightnings',
                     'multy store building',
                     'house,several floors',
                     'house,ribbon,bow',
                     'house,goft box',
                     'house,confetti',
                     'family',
                     'house, family',
                     'chair,desk,room'],

        'autocredit': ['car,ribbon,bow',
                       'car,ribbon',
                       'steering wheel',
                       'steering wheel,ribbon,bow',
                       'steering wheel,ribbon',
                       'car keys',
                       'car keys,ribbon',
                       'car keys into gift box',
                       'car,gift box',
                       'car,calculator',
                       'car keys,calculator',
                       'car,tree',
                       'car,fast driving,smoke'],

        'insurance': ['shield,car',
                      'shield,house',
                      'shield,building',
                      'shield,multi store building',
                      'steering wheel,shield',
                      'shield,medicine',
                      'medicine and coins',
                      'medicine',
                      'lock,shield',
                      'lock,coins',
                      'shield and banknotes',
                      'shield,coins',
                      'shield,coin',
                      'shield',
                      'bank,lock',
                      'shield,lock',
                      'coins,lock',
                      'steering wheel,shield',
                      'steering wheel,lock',
                      'shield,heart',
                      'lucky clover plant',
                      'shield and bag of money']
}
